### ISSUE TITLE
CORS 

### ISSUE THREAD

**Issue by JordanPinder** [jncc/web-mapper-core#65]
Hi

Issue loading layers outside Peterborough office. Seems to be a CORS problem, e.g.:

Access to image at 'https://staging.ows.emodnet-seabedhabitats.eu/emodnet/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng8&TRANSPARENT=true&LAYERS=eusm2016_caching_test&TILED=TRUE&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-2348145.5089206137%2C7200979.560689885%2C-2191602.474992573%2C7357522.5946179265' from origin 'https://prelive.mapper.emodnet-seabedhabitats.eu' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. 
 
This may be related to [issue 51](https://github.com/jncc/web-mapper-core/issues/51)? If so may not be CORS problem but potential IP restriction?

**Comment by andyb-esdm** [comment]
You may find this is due to browser caching.
When I'm in development mode, (localhost) I get CORS errors because I have cached tiles from downloaded when testing jnccdev-map.esdm.co.uk/
Try this to see if it's the case with you:
open developer tools in chrome (presumably) F12
right click on the refresh button in the top url bar
select 'empty cache and hard reload'

**Comment by LynnHeeley** [comment]
this is a staging server - is locked down to specific IPs. no issue. closed.
