### ISSUE TITLE
Schema mixed case conventions

### ISSUE THREAD

**Issue by JordanPinder** [jncc/web-mapper-core#73]
Apologies for the late notice with this one! I just noticed whilst doing some updates to the config database a couple niggly things around the use of mixed cases within the table and columns names. 

Issue is that with the use of capital letters it means we have to call tables / columns verbatim with the use of double quotes everytime, for example:

UPDATE public."Layer"
SET "Url" = '//staging.ows.emodnet-seabedhabitats.eu/emodnet_view/wms'
WHERE "Url" = '//staging.ows.emodnet-seabedhabitats.eu/emodnet/wms';

Whereas if they were all lower case by standard, it would be possible to call tables, columns etc. in a more loose fashion. 

Just had a fiddle with the schema naming conventions (e.g. changing BaseLayer to baselayer) and it seems these are also used in the endpoints. 

Would it take much work to alter the endpoints to be all lower case? Appreciate that may be a stupid question as it's not possible at this stage, so I should stress it's not a significant issue!

**Comment by andyb-esdm** [comment]
@JordanPinder one for @SimonAnnetts I think! :)

**Comment by SimonAnnetts** [comment]
In theory we could change all the table names to lowercase. I would have to annotate the C# classes in the web-api, specifying the lowercase table names as table mapping options. I'm sceptical that EF core migrations would successfully migrate the database tables due to the table relationships and foreign keys (the tables and constraints would have to be renamed in the right dependent order).  We could just drop the database and start again, and create a new initial migration that creates the db from scratch with the new table names. You would of course lose any data that you have in the db if we do this (this might be ok if all you have still is test data!)
I think this change would probably take me half a day to complete.
@JamesPe @GMDuncan - what do you think?

**Comment by GMDuncan** [comment]
Hmm maybe leave this as a low-priority task for now and see how much time etc there is later on? I think it's less urgent and more of an ease-of-use aspect for Jordan accessing the database directly (having to precisely reference the relationships in quotes etc) more than anything. There are likely higher priority tasks more worthwhile of the time/funds.
What do you think @JordanPinder ?

**Comment by JordanPinder** [comment]
@SimonAnnetts @GMDuncan yup no worries, as I mentioned it isn't a significant issue it's more for convenience than anything else - leave as it is :)
