### ISSUE TITLE
Support contract

### ISSUE THREAD

**Issue by JordanPinder** [jncc/web-mapper-core#87]
@andyb-esdm @JamesPe @SimonAnnetts, hope you're all well!

Is it possible to an updated figure for this month's support contract time please? Just so we can prioritise on our end what work we'd like focusing on this month :)

**Comment by JamesPe** [comment]
Hi,
Total of 23.83 hrs done to date – details below.
The IE11 issue took up a bit I’m afraid


35784: Call off support - Provide up to 8 hrs / month for 12 months
Add comment / log work done
Andrew Brewer
Tuesday, 02 Jul 2019
02hr15min
opacity control moved to active layers,  configurable gazetteer placeholder
Edit
Andrew Brewer
Monday, 01 Jul 2019
02hr00min
further ie11 positioning issues (stretched icons in controls toolbar) due to ie11 svg bug
Edit
Andrew Brewer
Friday, 28 Jun 2019
05hr30min
icon issues in ie11 - replaced all webfont references with svg icons
Edit
Andrew Brewer
Thursday, 27 Jun 2019
02hr00min
investigation - web fonts not displaying in some ie11 browsers
Edit
Andrew Brewer
Wednesday, 26 Jun 2019
01hr30min
gotoxy and deployment to staging
Edit
Andrew Brewer
Friday, 14 Jun 2019
20min
replace 'includes' with 'indexOf' for IE11 compatibility
Edit
Simon Annetts
Wednesday, 12 Jun 2019 at 07:10 PM
20min
filters discussion with AB
Edit
Andrew Brewer
Tuesday, 11 Jun 2019
03hr30min
separating cql_filter and viewParams, proxy with SA, updating issue on github
Edit
Simon Annetts
Tuesday, 11 Jun 2019 at 05:09 PM
02hr00min
ogcproxy #82
Edit
Andrew Brewer
Monday, 10 Jun 2019
03hr00min
started work on mixed filters (also investigated templated filter parameters)
Edit
Andrew Brewer
Monday, 10 Jun 2019
20min
github issue getfeatureinfo and transparent polygons to gmduncan
Edit
Andrew Brewer
Friday, 24 May 2019
30min
upgrade to angular 8
Edit
Andrew Brewer
Monday, 20 May 2019
30min
replies and discussion on mixing complex and simple filtering with GMDuncan
https://github.com/jncc/web-mapper-core/issues/81
Edit
James Perrins
Friday, 11 Jan 2019 at 10:30 AM
05min
Logged task
Edit
James Perrins
Friday, 11 Jan 2019

Following the successful implementation of the web mappers the Contractor will provide up to 8 hours per month for 12 months supporting the maintenance and development of the web mappers, including support for general use of the system, bugfixes, minor functionality improvements and to resolve issues with library updates.

The Contractor’s project manager will provide a time estimate for work within two working days of being notified by the JNCC contract manager that support is required. Following receipt of a time estimate, work will be approved by the JNCC contract manager in advance of work commencing and logged in a maintenance and development log. Up to four unused hours per month will be carried forwards to the following month.
Edit
Files - none

**Comment by JordanPinder** [comment]
@JamesPe thanks for that. Do you have figures of how much (if any) was carried over from last month, and what the balance is for July?

**Comment by JamesPe** [comment]
That’s the total for the year – so you can work it out
We aren’t that fussed about month to month and carry over.  So long as we aren’t over at the end of the year and there isn’t a massive amount asked for in the last month we are happy to be flexible

**Comment by JordanPinder** [comment]
@JamesPe @andyb-esdm @SimonAnnetts sorry for the delay. Below is a list of things for this month. If you can give rough time estimates for each that'd be great and then we'll decide which one to go with. 

- ‘Remove layer' hover text briefly appears in the top-left of the mapper when a layer is removed from the Active Layers window

- Highlighting features when clicked on in the mapper (i.e. those features which are shown in the FeatureInfo window)

- Filter menu scrolling: currently an issue where large filter windows disappear off the bottom of the mapper and cannot be scrolled. Will also ask for the filter window to close when “apply” is clicked.

- Search box: clearing the previous search when the box is clicked on for a new search

**Comment by JordanPinder** [comment]
@JamesPe @andyb-esdm @SimonAnnetts in addition to the points above, we also have another addition:

- Hierarchical filtering: allow filter selections to include all habitats are finer detail (i.e. child habitats). For example, filtering by A4.1 should return A4.11, A4.12, A4.13 etc. 

If you're able to give rough time estimates for this addition and the previous 4 points that'd be great.

**Comment by andyb-esdm** [comment]
@JordanPinder @HelenwoodsJNCC
Sorry for the delay in my reply.
I've edited your comments to number the requirements, so we can reference them more easily.

1. I know. It's terrible and it bothers me. But it's quite a hard one to solve. Tooltips work by detecting when the mouse cursor is over an element and disappearing when the cursor exits the element. When you remove a layer, the element is no longer there so you don't get the event saying the cursor has exited the element. My 'fix' to this was to get the tooltip to disappear after an interval (see all the other tooltips - they only stay on screen for a short time). But that interval is long enough that you see the tooltip briefly when you remove a layer. I think I could wire up a custom event to clear the tooltip when an element is destroyed but it would take a bit of thought. Hard one to estimate but could be a few hours and up to half a day?
**Estimate:  4h**

2. There isn't a standard way of doing this with a WMS as far as I'm aware. But some approaches are discussed here: https://gis.stackexchange.com/questions/173867/how-to-highlight-a-feature-in-wms-map-image Here, the same layer is requested twice, once with the the layer filtered to the selected feature and with a different style applied. There may be other ways to do this too. Will discuss with @JamesPe and other colleagues before giving an estimate.
**Estimate: TBD**

3. Yes. This didn't get the styling attention it deserved. It needs to have a max height based on the viewport height and then present a scrollbar (a bit like active layers).
**Estimate: 2h**

4. Should be straightforward.
**Estimate: 1h**

5. At first glance, I think this would require a database change to represent parent-child relationships, new UI to display a tree and some thought about how all this translates into a filter. We'd need a discussion with you to agree on how all this fits together so there's a bit of meeting time in this (provisional) estimate.
**Estimate: 12h**

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm thanks for looking into the potential support items. We will have an internal chat about 1,2 and 5 to try and prioritise our requirements. But we are happy for you to go ahead with points 3 and 4 - filter menu scrolling and search box clearing.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC okay - @JamesPe will review these too when he's back. He may have some alternative solutions.

**Comment by JamesPe** [comment]
2. I have done both of these in the past.  WFS I think is definitely nicer.  Not sure how easy that is to do Andy when everything else has been set to use WMS, and also whether this would mean all the 
mapping services have to be setup to allow WFS ?

**Comment by JamesPe** [comment]
5.  There is an approach to this where because the codes themselves are all hierarchical you can use a wildcard on the end of the code and select child codes that way.

And if the table needs to appear as a popup hierarchically (which is a different issue and strictly not what was asked for here) - you can use a flat table to represent - where there is simply a field in the table that identifies the parent code of each code.  That way a hierarchy can be dynamically determined.

**Comment by andyb-esdm** [comment]
@JamesPe thanks. So the requirement for 5 wouldn't allow you to click several nodes and want to include all children of these? e.g. A1* OR A2*?

@HelenwoodsJNCC @JordanPinder 
1. Is now complete. I discussed it with a colleague (Stewart Bellamy - thanks) and he said 'why don't you dismiss the tooltip when you click?' So I tried it and it worked! I don't think this has any bad side-effects. It means the opacity tooltip (for example) disappears when you click on the control but that doesn't jar. It took 20 minutes to edit and test. Complete failure of imagination from me.

**Comment by JamesPe** [comment]
Well if you had a hierarchical picker it could be Like A1* or  like A2* could it not ?

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm @JamesPe thanks for sorting point 1, glad it turned out easier than expected. 

We have another potential support contract item we would like to get your thoughts on:
6. The addition of Google Tag Manager script to the mappers so that their usage can be monitored in detail via Google Analytics. We would ideally like to track things like which layers are being used, but it would be good to get your thoughts on how easily or not this can be achieved.

**Comment by JamesPe** [comment]
Easy I think to add basic google analytics - but that wouldn't necessarily get the level of detail you appear to be after.
I'll leave Andy to comment on ease or otherwise of integrating google tags for layers etc.

However couldn't you achieve similar by logging tiles served from geoserver ?

**Comment by GMDuncan** [comment]
Just checking - would that also pick up non-mapper interaction with geoserver (e.g. people using the webservices with desktop GIS) and provide differing metrics dependent on screensize (because the layer request would be result in more tile downloads per layer)? Could maybe do some data munging to get around those, however.

**Comment by JamesPe** [comment]
Hmm - Graham - yes it would pick up all use - whether you could separate it would I guess depend on how it was being called from desktop - if its using the same tiled service as the mapper it might be tricky.

However simply recording the adding of a layer doesn't tell you much about use really I would have thought - it could have been added and almost instantly discarded - or had 10,000 tile draws as it was used in anger.  For that you need to look at tiles being served I would think.

**Comment by GMDuncan** [comment]
QGIS, I think, defaults to requesting the entire canvas as a single image rather than tiles, unless the user specifies a tilesize, so potentially could slightly mitigate the desktop issue by filtering out desktop requests but looking for requests not containing "&TILED=TRUE" or something.

Agree on accidental layer activation and meaningful stats though. Not sure if google tracking could filter out layer activations where the the same layer was recorded as deactivated within n seconds? Seems quite complex behaviour.

**Comment by andyb-esdm** [comment]
I'm not familiar with Google Tag Manager and it's relationship with google analytics - sorry. But it sounds like you might go for geoserver logging now?

I do know that setting up google analytics with the mapper should be straightforward. And, from a quick scan of the docs, it looks like we could use analytics' custom event tracking to monitor anything you wanted really from within the application e.g. adding layers, filtering etc.
A lot of these actions are already represented as data sources in the app that components can subscribe to, so hooking up something to send an event to google analytics when a layer is added (for example) looks straightforward.
I think it would take an hour or two to get it hooked up and working in principle and then we could add events for actions you choose. But I won't take this any further until you settle on an overall approach.

**Comment by GMDuncan** [comment]
Quick follow up question, assuming the code will be part of the core shared between the mappers, is it feasible that this could be configurable to enable or disable?

(EU are not keen on Google Analytics in general, so there is the possibility that the Emodnet mapper would need Google analytics completely disabled, is that right @JordanPinder ?)

**Comment by andyb-esdm** [comment]
@GMDuncan Yes. That would be easy to do as a configuration option if we went that way.

**Comment by jonparsonsjncc** [comment]
Hi @andyb-esdm 
We would like to implement google analytics, added by google tag manager, to enable us to report on in map activity
I have created a new ticket for the task of adding the google tag manager code
please refer to 
https://github.com/jncc/web-mapper-core/issues/91
happy to discuss if any further information needed
thanks

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm another potential support contract item is related to the loss of the base map imaging when zooming in. This is particularly an issue on bing maps where it stops returning images for the open ocean areas after zoom level 13, and this looks particularly odd around the coastal sites: 
https://jncc.gov.uk/mpa-mapper?zoom=14&center=-1.598,55.395&layerIds=43,44,45,46,71,78,67,74&baseLayerId=-2&activeFilters=

We have some sites that are quite small with fine level feature distribution detail that users will need to zoom right into. Im assuming this is a limitation with Bing maps but is there a way we could switch to a plain background if no image is returned for a tile?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC  Sorry for the delay in my reply.
You're right this is a limitation with Bing Maps. For some reason marine tiles are replaced with a placeholder at much lower zoom levels than for terrestrial areas and it looks pretty jarring on that permalink. We've looked at a few options - though none of them are ideal.

1. We could set a maxzoom on the layer to force the tiles to stretch - instead of showing a placeholder. But this applies to all tiles - not just the marine ones and you lose quite a bit of resolution if you set it to 13 (see below)

![image](https://user-images.githubusercontent.com/31621682/63171444-7f1d4300-c033-11e9-8ef9-29fbdbbb2a00.png)

2. We could switch the layer at zoom 14 to OpenSteetMap. But this might be equally jarring to users.

3. We could override the function that loads the tiles (https://openlayers.org/en/latest/apidoc/module-ol_Tile.html#~LoadFunction). We could attempt to identify placeholder tiles as they are loaded and replace them with a new placeholder (e.g. a plain blue tile). The file name of the tile won't tell use if it's a placeholder or not but we could check its size, format or even content. This is a bit involved but might be worth an hour to test its viability.

**Comment by helen-lillis** [comment]
Hi @andyb-esdm , my views on the placeholder tiles issue are:
1. it would be a shame to lose the detail, so I'd rather we didn't do this
2. we discussed this option but thought it might be annoying to users wanting to see the coastline.
3. I think it would be worth looking into.

Could an alternative option be to use the EMODnet Bathymetry tile service as an alternative default? ([https://tiles.emodnet-bathymetry.eu/]) See it in action here on the EMOD Bathy portal: [https://portal.emodnet-bathymetry.eu/]. This would have the added benefit of showing a bit of bathymetry for context.

**Comment by HelenwoodsJNCC** [comment]
@JamesPe can we get your thoughts/time estimates on the following issues as potential support work:
7. The ability to set the default drawing order for active layers displayed when the mapper is first started up
8. Update to the scroll bar to something a bit better looking and also something that is compatible with mobiles/tablets - the scroll bars don't currently appear when viewing the mapper on a tablet. 
9. Update the map info box title - currently when the window opens it has a title of MPA/EMODnet. Can we change this to something more relevant e.g. Map Information

**Comment by JamesPe** [comment]
These really need @andyb-esdm  input but:
7.  Should be possible - I assume this is a default order for all users not user specific?  But how does this differ from the layer order that you currently specify when setting up a map group and layer ?  I assume you are wanting the draw order to differ from the layer control order?
It would need a new field in the API tables and I guess a sort order to be set across all layer groups.  So possible - but not trivial - maybe a day or two
8. That really is one for Andy - I would guess it can be changed - but how mobile firendly taht would end up I can't say
9.  Do you mean here?
![image](https://user-images.githubusercontent.com/10585763/63502614-d99c2080-c4c5-11e9-8ceb-cc806e050578.png)
I can't believe that would be difficult to change

**Comment by HelenwoodsJNCC** [comment]
Thanks @JamesPe, I know @andyb-esdm is on leave until September so I'm happy to wait for his comments, and then we can prioritise the issues.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @JamesPe 
7. Fortunately, we have two data structures that represent the layers: the layer config and a separate array of visible layers. So, if we had a default draw order column in the layer configuration, then we can sort by this value in the visible layers array, without affecting the layer order in the layer configuration.
For the API, the schema change (and updating the code to reflect this) would likely be a couple of hours and then updating the front end with a slightly different configuration object and doing the sort would likely be another couple of hours. Add an hour for deployment and contingency.
**5h estimate.**
8. This is tricky. Scroll bars are one of the last bit of browser UI that are not covered by web standards for styling. It's coming, but currently you can only user vendor-specific styling (not supported by all browsers) or write custom JavaScript for scrollbar handling. I've just tested styling scrollbars in chrome, firefox and edge - all required handling this in a different way or didn't work. I could style chrome with the webkit prefix and firefox using the draft W3C specficiation. But I couldn't style Edge (yet) and I don't think this will ever be supported in IE11.
So the only solution across all devices currently looks to be custom JavaScript. There are some Angular packages available for custom scrollbars and one is used here:
https://www.primefaces.org/primeng/#/scrollpanel
This worked well on all desktop browsers but didn't scroll for me on Android (even though they looked nice).
I would have to research this a bit more but perhaps this is something to put to one side until we make the mapper more mobile friendly in general?
9. Currently the map info component displays the name of the map instance. If you just want it to show some static text (e.g. Map Information), then it's a 20 minute job to change that an re-deploy.
If you want it configurable, then the quickest way would be via the config files and an update to the code - still under an hour.

**Comment by HelenwoodsJNCC** [comment]
Thanks @andyb-esdm. When you get a chance can you start work on the following support issues:
3. Add a scrollbar to filter window
4. Search box clearing: clearing the previous search when the box is clicked on for a new search
7. Ability to set the default drawing order of layers
9. Map info box title update - @JordanPinder are you happy enough to have a standard title i.e. Map information, or would you want this to be configurable?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Yes.
Is this as well as, or instead of, google tag manager work with @jonparsonsjncc and handling placeholder tiles?

**Comment by jonparsonsjncc** [comment]
Hi @andyb-esdm<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fandyb-esdm&data=02%7C01%7CJon.Parsons%40jncc.gov.uk%7Cfd469e9343ab41d62b4408d7310b4778%7C444ee4e8b2fd491d8c318b0508370a6b%7C0%7C0%7C637031796832167212&sdata=MGZkOtpS9eQ%2FW4KEnfdyzBd3oyHRf3Npmbf8%2FAfSqfo%3D&reserved=0>

Welcome back

Please let me know when the IDs for the layers are in the live site and I will then add the google tags

Here’s a link to the report showing the data so far
https://datastudio.google.com/reporting/1XY1N27MJ37mp59XZZeRBhAICkq8-VSjo/page/WyBv
with a new section added ready for the layer data

Just to let you know I am off for a week as of this Friday. So if not possible before then no rush and I will deal with on my return.

Thanks

Jon

**Comment by andyb-esdm** [comment]
HI @jonparsonsjncc 
Okay. I will know by the end of today how my time is allocated over this week and next.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm Im happy for you to finish the google tag manager work with @jonparsonsjncc before you start on my other issues. Once these 'smaller issues' are out of the way we plan to revisit the large items like placeholder tiles and hierarchical filtering - depending on how much time we have left. I will open new issue for these as they still require a bit of discussion and things might get lost in this thread.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC 
Filter overlay size and overflow issue now fixed hopefully. Internet Explorer 11 caused some problems here because it made the new scrollbar overlaps the internal ones. So I've had to work around this by padding the right of the controls by 20px.
This change is only http://jnccdev-map.esdm.co.uk/ at the moment.
@jonparsonsjncc I'll do the GTM ids next (this week).

**Comment by jonparsonsjncc** [comment]
Thanks Andy

I am off tomorrow and at the FOSS4G on Thursday Friday this week so may not have too much time to action if after Wednesday lunchtime

I was also thinking it might be best to apply the new tag to one of the layers first and let me test to see if it records ok - before applying to all

Its only a quick job to add in one and test so should be able to do this between conference talks if needed

Cheers

Jon

**Comment by HelenwoodsJNCC** [comment]
Thanks @andyb-esdm scroll bar is working for me.

**Comment by andyb-esdm** [comment]
I've added the WMS layer ids to the divs that toggle the layers on and off. I'll update issue #91 with details.

**Comment by HelenwoodsJNCC** [comment]
Thanks @andyb-esdm the google analytics stuff is all up and running. So I think the only support contact things open at the moment are:
- Search box clearing: clearing the previous search when the box is clicked on for a new search
- Ability to set the default drawing order of layers
- Map info box title update - Update to 'Map information'

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Okay - 1 and 3 are relatively trivial. I'll have a chat with @SimonAnnetts about the API for default drawing order. I'll review when I can do this in the next few days and let you know (I'll pop it in my calendar).

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm all working well at this end. Thanks.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @JordanPinder I've spoken to @SimonAnnetts about the default active layer order. The code changes required are quite simple and we think around 2h to make the change between us. We will add a new column to the Layer table called LayerDefaultOrder, which will be a number. The lowest number across all layers will be at the top.

However, we're not sure how easy this will be to deploy. We need to do a database schema and API update on your servers but they may be locked down.
It would be good to speak to someone for both EMODnet and MPA about this if possible.

@JordanPinder The deployed EMODnet version of the mapper is quite a few versions behind the deployed MPA mapper. We can update it when you are ready.

**Comment by JordanPinder** [comment]
@andyb-esdm yes I've been meaning to get the EMODnet versioning sorted! Are you able to deploy this yourselves or do you also need input from our DDS team? If you do not need DDS input please feel free to deploy to the staging environment and I can give it a check :) 

In terms of deploying the database schema and API update for layer ordering I'm sure we can get something arranged, although might need @paul-gilbertson input. I feel we did something similar in the early stages of the mapper development for granting you access to the servers?

**Comment by andyb-esdm** [comment]
@JordanPinder Thanks for that. We'll make the change locally then get you up to date (potentially with help from DDS team). Will be in touch soon!

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @JordanPinder 
@SimonAnnetts has updated the API and database schema and I've updated the mapper. So default order for visible layers is now implemented when the map first loads.

There's a new column in the Layer table called LayerDefaultOrder. This is a numeric value that defaults to 0. When visible layers are loaded from the api, the mapper will sort all visible layers in ascending order. So leave the one you want at the top with this value 0 and then set a higher value for the other visible layers to put them underneath.

We've only deployed to https://jnccdev-map.esdm.co.uk/ so far. I am not sure we have permissions to update the database schema with the web api user account. If that failed, then the api and database would be out of synch and this might break the website. So I think we do need advice from your DDS team here.

**Comment by jonparsonsjncc** [comment]
Hi Andy

I will pick this up with the team

Jon

**Comment by andyb-esdm** [comment]
Hi @mattdebont 
The API uses code-first migrations. This means the application updates the database schema (if necessary) when it starts up. So, ideally, the login/user on the connection string in the application configuration (appsettings.json) will have alter database rights on the database. I believe that connection string will be called 'JNCCWebApiDatabase' in the appsettings and you can get the login from it. Is this something you can check (the user permissions)?

You may find that the user does have these permissions. It's us being cautious.

Agree it would have been much simpler to alter the schema directly but I suspect the migrations will check and populate an audit table (__EFMigrationsHistory in SQL Server).

If this isn't something that can be easily checked/changed, then we could look into creating a script that would mimic what the code-first migrations do (do the schema change, update __efmigrations) but we would need to check exactly what that is first.

**Comment by jonparsonsjncc** [comment]
Hi @andyb-esdm wondering if you are free for a call to discuss this

**Comment by jonparsonsjncc** [comment]
Hi @andyb-esdm 
after our catch up last week - wondering if you are ready to do a push today to test everything out
let me know
thanks

**Comment by andyb-esdm** [comment]
HI @jonparsonsjncc tried calling you and have emailed.

**Comment by jonparsonsjncc** [comment]
@andyb-esdm @mattdebont 
Now the permissions have been set and the process works
we will lock down these permissions again for security
@andyb-esdm let us know when you need to run the process again and we will put the permissions back
hope this resolves this ticket and we are all happy to close it
