### ISSUE TITLE
Install google tag manager code into https://mapper.mpa.jncc.gov.uk

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/web-mapper-core#91]
To allow injection of our google analytics code and tags specific to individual events, to allow us to report on individual click actions - please initially add the attached code

[mpa-tagmanager-code.txt](https://github.com/jncc/web-mapper-core/files/3477571/mpa-tagmanager-code.txt)

**Comment by jonparsonsjncc** [comment]
Once this code is added I will be able to push in the analytics code to the page and also set up and inject the specific tags - which will be rendered in the code in the browser on opening.

We will see if we can lock our tags on to elements of the code so they will fire an event in analytics but we think it would be a lot easier if each input had a unique ID eg:

For a checkbox - then this existing code
<input _ngcontent-neu-c19="" type="checkbox">
if it could be
<input _ngcontent-neu-c19="" type="checkbox" id="Fish-point">

and this adding as an id for drop down - then this existing code
<div _ngcontent-neu-c10="" class="layer-group-selector">
if it could be
<div _ngcontent-neu-c10="" class="layer-group-selector" id="species-protected-offshore">

We will try to lock on to the code as it is - but would appreciate your thoughts on time to add in these additional unique IDs for each dropdown in the map

thanks

**Comment by andyb-esdm** [comment]
@jonparsonsjncc 
There shouldn't be a problem adding the google tag manager code. I haven't tested yet but online articles suggest it lives happily with Angular.
But in #87 @GMDuncan was concerned tracking code might not be appropriate for EU websites. I considered having a configuration option for using GA directly but now I understand what Google Tag Manager is, I think it might be an idea to branch the code for this. This would be easy to keep up to date by merging the main branch in periodically.
Alternatively, I could look at conditionally rendering the tags based on a config setting but this adds complexity and I'm not entirely sure Angular will allow it.
So I'd suggest a branch for supporting GTM. What do you think?

I've investigated binding element ids to a test layer name and that works quite nicely in a simple use case. So that would certainly be worth trying.

![image](https://user-images.githubusercontent.com/31621682/62693360-3d085780-b9ca-11e9-8220-0b6d1c328325.png)

![image](https://user-images.githubusercontent.com/31621682/62693899-3c23f580-b9cb-11e9-833a-e1ac2731ba3d.png)


Since you will be doing most of the work managing events via GTM, adding the script should take very little time but I guess we'll need to coordinate a bit so you can test. Maybe an hour at some point to check it's all working?

The controls are already data bound to the layer configuration information so, again, it should be reasonably trivial to do this (assuming it 'just works'). We just need to agree where best to put them.

The one unknown for me is whether Angular will pass up events to GTM in a way you can pick them up meaningfully but we'll find that out pretty quickly.

So full estimate is no more than an hour or so if it all works as planned.

**Comment by GMDuncan** [comment]
Hi, I'd get clarification from @helen-lillis on the EU + Google aspects as she'll have a more up to date knowledge of their views than me, I just know it was commonly discussed at the EMODnet technical working groups when I attended (and the reason why, for example, Matomo was used as the tracking platform across the initiative)

**Comment by jonparsonsjncc** [comment]
Hi @GMDuncan - I can confirm that google analytics should NOT be used for emodnet, we have just been through a GDPR review with this site and it was clear that google anaytics was not accepted. So we do need to think about options to restricting it to only the https://mapper.mpa.jncc.gov.uk/ domain.

**Comment by jonparsonsjncc** [comment]
@GMDuncan in google tag manager - once the code is in place, there is a test mode in tagmanager with allows browsing of the page with an overlay which shows in a nice visual way when the tags fire etc, it also highlights if there are any other issues with the code. So once you have added its very easy to for me to test if all OK.
great to see that its also easy for you to add in the IDs - it makes the adding of the tags so much easier to identify
thanks for you help

**Comment by jonparsonsjncc** [comment]
BTW - we are using google data studio to pull together a dashboard of the relevant events together with top level visitor numbers - we have done it on another mapping project just recently - happy to share the dashboard of that - and the new one for the MPA when set up if of interest.

**Comment by andyb-esdm** [comment]
@jonparsonsjncc I've created an 'analytics' branch, added the GTM scripts and deployed a production build to mapper.mpa.jncc.gov.uk.
Getting a 404 so I guess there's something you need to configure?
![image](https://user-images.githubusercontent.com/31621682/62783655-be3c1900-bab4-11e9-94ff-07c794f2e933.png)

**Comment by andyb-esdm** [comment]
I haven't changed the code yet because we need to discuss and test but wanted to see if this works.

Yes, would be very interested to see what you have done for past mapping projects.

**Comment by jonparsonsjncc** [comment]
Hi @andyb-esdm thanks for doing this - I have now published the container which has the google analytics code in it - and all working fine - see below of the tag manager test overlay page highlighting the analytics tag has been added and successfully fired on the page
![image](https://user-images.githubusercontent.com/50585245/62788989-e8470880-babf-11e9-8048-dda820bcf1b1.png)
so the door is ope now for me to add in other tags which latch on to you code - let me know when these are in place

**Comment by jonparsonsjncc** [comment]
hi @andyb-esdm FYI - here's a screen shot of the dashboard for a new map we working on
![image](https://user-images.githubusercontent.com/50585245/62789300-88049680-bac0-11e9-8153-8f794b0cb615.png)
will be putting something similar together for MPA

**Comment by jonparsonsjncc** [comment]
Hi @andyb-esdm I have deployed some tags and these are recording nicely - see below - but change date range to today
https://datastudio.google.com/open/1XY1N27MJ37mp59XZZeRBhAICkq8-VSjo
but have a couple of questions - are you free for a call
my skype id is jonparsons

**Comment by andyb-esdm** [comment]
@jonparsonsjncc 
I've updated the mapper so that the id of the div you click to toggle the layers off and on has an id equal to the layer name in geoserver e.g. 'mcz' for marine conservation zones.
Drop me a line or skype and we can talk through it.
