### ISSUE TITLE
Highlighting features

### ISSUE THREAD

**Issue by HelenwoodsJNCC** [jncc/web-mapper-core#93]
We briefly discussed this in issue #87 but we would like to revisit this issue now some of the smaller support contract issues are closed. 

As a reminder we would like to be able to highlight a feature when it is clicked on in the mapper (i.e. those features which are shown in the FeatureInfo window). @andyb-esdm @JamesPe did you ever determine if this was a possibility using WMS or is there a requirement for all layers in WFS?

**Comment by JamesPe** [comment]
I have done similar in the past but I really can't recommend it.  Somehow you have to identify the polygon on the image that you have selected and then get geoserver to apply a different styling to it (probably requires it bring brought in as a new WMS layer ontop of everything else).  So it definitely requires map requery and refresh.

Compared to WFS where you just highlight the polygon that already exists browser side almost instantly.  A situation where you dragged down a WFS polygon to overlay on the WMS image would be another option maybe.

See what @andyb-esdm  thinks - but I think it may fall into the "possible but you really don't want to do it that way" category

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @JamesPe 
Yes this is a bit tricky with a WMS.

- You could do a separate WMS request with a CQL_FILTER of the bounding box of your click and overlay it on the map (using a different legend). This is James suggestion above.
- GetFeautreInfo can also return features in GeoJSON format, which we could overlay as a vector layer. Unfortunately, it's low resolution (see image below) so it might look a bit rubbish. I don't know if resolution can be configured.
- We could do a separate WFS GetFeature request on click and get the full resolution polygon back and overlay it. This would require turning on WFS for your layers on geoserver.
- We could support WFS as a layer source in the mapper. This would be a good addition. However, some of the SPAs and SACs have a lot of vertices around the coast so this might affect performance/bandwidth.

I haven't tried to do this with WMS before so I defer to James experience here. Maybe the WFS GetFeature approach strikes the right balance between simplicity and bandwidth concerns?

![image](https://user-images.githubusercontent.com/31621682/68936231-02b11200-0792-11ea-802b-70fdb77be642.png)

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm @JamesPe thanks both. Sounds like we would need to develop this using WFS. We don't currently have WFS layers enabled on the MPA mapper, @JordanPinder @helen-lillis are the EMODnet layers available as WFSs?

**Comment by JordanPinder** [comment]
@HelenwoodsJNCC @helen-lillis @andyb-esdm @JamesPe morning all! Yes the EMODnet GeoServers have WFS enabled but only on our "public" workspaces (i.e. https://ows.emodnet-seabedhabitats.eu/emodnet_open/wfs, https://ows.emodnet-seabedhabitats.eu/emodnet_open_maplibrary/wfs), whereas we have all public and view only data held on our WMS workspaces (https://ows.emodnet-seabedhabitats.eu/emodnet_view/wms, https://ows.emodnet-seabedhabitats.eu/emodnet_view_maplibrary/wms); would this only be possible with layers/features that are available publicly to download as opposed to those which are restricted/view only on the WMS workspaces?

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm - your option 3 above (GetFeature request) sounds like a good balance to me @JordanPinder @helen-lillis do you agree or would you rather option 4? Is there anything we need to do at our end for this other than have the WFS enabled?

A couple of other questions:
Would this work on the top layer only or potentially all the layers that are switched on?  
Are there a lot of changes required to the code from your perspective? I'm just trying to get a handle on the time requirement for this ask.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC 
I think what we need to do is get all of the WMS layers at the pixel that the user clicks (the mapper already does that) and then call the equivalent GetFeature for the WFS equivalents as well as GetFeatureInfo on the WMS.
Joe, a colleague of mine, has done something similar retrieving equivalent features and using them as a highlight.
When we get the features back, we would add them all to a new highlight layer. We would style this layer with some low opacity highlight so that it looks like the underlying WMS is highlighted.
So mapper will need:

- A new highlight layer
- Changes in the code to call GetFeature from the WFS for each WMS
- Aggregate the returned features and place the on the highlight layer
- Make sure this doesn't introduce any new complexities

I think this can be done in under a day when you have the layers available.

**Comment by HelenwoodsJNCC** [comment]
Thanks @andyb-esdm. Im just wondering how best to set up the highlight layer? I'm guessing we just set up a new selection layer in the api table using the WFS url and create a highlighted style? But we won't be able to specify a layer name in the api table as this will be variable depending on which layers are turned on. Apologies if i'm missing something obvious!

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Sorry I was using the royal 'we', which has confused things. JNCC just need to make the WFS services available from geoserver. The highlight layer will be a client side map layer in the mapper itself (my problem).

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm phew, thanks for clarifying!

**Comment by helen-lillis** [comment]
> @andyb-esdm - your option 3 above (GetFeature request) sounds like a good balance to me @JordanPinder @helen-lillis do you agree or would you rather option 4? 

Hi @HelenwoodsJNCC I have no preference!

**Comment by hughlewiswright** [comment]
Helen is on leave from tomorrow so I'll try to cover in her absence if something crops up (with Jordan's help)

**Comment by HelenwoodsJNCC** [comment]
Hi @andyb-esdm just checking in to see if you need anything further from us before you proceed?

**Comment by andyb-esdm** [comment]
HI @HelenwoodsJNCC Yes. We need WFS layers enabled on the MPA server.  I can pick this up with someone who manages the layers if you like.
@JamesPe does this solution sound okay to you?
https://github.com/jncc/web-mapper-core/issues/93#issuecomment-563968070

**Comment by HelenwoodsJNCC** [comment]
Hi @andyb-esdm I think the plan was to test this using a set of Emodnet layers which are already WFS enabled - right @JordanPinder? Not all of the MPA layers can be WFS enabled and we haven't yet divided them up.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Sorry I didn't pick up on that from the earlier comments. In that case, I can test against the EMODnet layers.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC I did some prototyping work on highlighting clicked features yesterday.

1. For EMODnet at least, the WMS are organised into layer groups on geoserver. This is so tiles of appropriate resolutions can be displayed at different zoom levels. So it's the layer group - not a specific layer - in the mapper's layer configuration. GetFeature for WFS needs a specific layer. So I think we need another column in the database, where the URL of the WFS is specified. For the prototyping work, I hard-coded the MSFD layer url.

2. First I tried to use the WFS GetFeature request with a bounding box (1m2) in the URL like this http://..../geoserver/wfs....bbox=10,20,11,21 But this was over-selecting features. Large areas of the layer were being selected. @SimonAnnetts recognised that using a bounding box filter returns all the features whose bounding boxes intersect the bounding box! Fortunately, there is an OGC filter where you can get back features that strictly intersect a geometry but this was a bit more complicated to set up. Using the OGC filter (which is a generic filter) requires you to specify the column names you are filtering. So the mapper needed to know that the database geometry column was called 'geom' to do the intersection. So, if we used this approach we would either need to have another column in the mapper configuration that gives the name of the geometry column or assume it will always be called 'geom'.

3. Some of the habitat layers have very large, complex polygons. For the MSFD layer, retrieving a single full resolution polygon took around a second i.e. a noticeable delay to select it. So I used the layer generalised to 800m. This returned near instantly. It means the selection doesn't exactly match the WMS polygon but I think it looks okay even when you zoom right in (comparison below).

![image](https://user-images.githubusercontent.com/31621682/73060805-8f620580-3e90-11ea-8d45-c7b668711916.png)

![image](https://user-images.githubusercontent.com/31621682/73060810-9557e680-3e90-11ea-815e-1402df5b31da.png)

4. If you have mutiple active layers, then presumably you would have multiple highlighted polygons - one for each layer. I think that would look okay for MPAs but might be very messy or confusing for EMODnet. We could set it so that only the feature on the top layer is selected. Alternatively, given the considerations about polygon complexity above, we could have a setting in the app.config file called 'highlightselection' or similar set to true/false. This would toggle the functionality for different map instances.

Here's a screenshot of the selection on the MSFD layer.
![image](https://user-images.githubusercontent.com/31621682/73061194-7f96f100-3e91-11ea-8776-b7d9f1001666.png)

This prototyping took 6h 30m due to this unforeseen complexity (sorry). There's a bit more to think about and for you to decide too. If we go ahead, we will need a schema change and an update to the API. That will probably take @SimonAnnetts a couple of hours. I will need to generalise the mapping code so it will work on any layer and potentially add the toggle in config. That will probably be 4 or 5 hours. So total estimate to finish this to production quality is 7 hours. We can pick this up next week if you would like. Let us know.

**Comment by andyb-esdm** [comment]
Hmm. It does matter what resolution WFS we use. I can't select these red polygons because they aren't there in the underlying 800m generalised layer.

![image](https://user-images.githubusercontent.com/31621682/73062322-064ccd80-3e94-11ea-9fac-11bb8c7007bc.png)

But it works exactly right with full resolution

![image](https://user-images.githubusercontent.com/31621682/73062412-401dd400-3e94-11ea-84e7-b0c25137bbc4.png)

**Comment by GMDuncan** [comment]
hi @andyb-esdm . Sorry, I'm coming into this halfway so I'm fairly certain it'll have been answered previously, but I'm intrigued as to why this isn't being handled with a duplicate WMS call with added filter parameters.

Pulling out a single polygon based on a click should... I think be handleable but the INTERSECTS([geom_column], [intersect_geometry) filter. So for the layer that is being "selected", you'd fire off an identical WMS call (or multi in the case of tiles), but add an INTERSECTS( ) filter to the CQL_filter value. If there's already a CQL_FILTER going on you could just chuck an ADD operator in between.

Using this as an example, the following request has a habitat filter on it:
[Full tile](https://ows.emodnet-seabedhabitats.eu/emodnet_view/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng8&TRANSPARENT=true&LAYERS=eusm2019_group&TILED=TRUE&CQL_FILTER=web_class%20IN%20(%27A5.3%27%2C%27A5.33%27%2C%27A5.34%27%2C%27A5.35%27%2C%27A5.36%27%2C%27A5.37%27)&20AND%20INTERSECTS(geom,%20POINT%20(4.713%2057.616))&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=508764.86026613414%2C7866287.454884058%2C547900.6187481444%2C7905423.213366068)

And this one uses an additional intersects statement:
[Point intersect](https://ows.emodnet-seabedhabitats.eu/emodnet_view/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng8&TRANSPARENT=true&LAYERS=eusm2019_group&TILED=TRUE&CQL_FILTER=web_class+IN+(%27A5.3%27%2C%27A5.33%27%2C%27A5.34%27%2C%27A5.35%27%2C%27A5.36%27%2C%27A5.37%27)+AND+INTERSECTS(geom%2C+POINT+(524203.482146+7892069.96585))&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=508764.86026613414%2C7866287.454884058%2C547900.6187481444%2C7905423.213366068)

You could request a "featureSelection" style on the layer to make it red etc? 

I can see a few issues with this, mainly that all the geometry columns need to be consistently named and the point needs to be (i think) in the same projection as the layer so it oculd be an issue if a layer isn't in web mercator?

Sorry if stepping on toes - i was just intrigued!! :)

**Comment by andyb-esdm** [comment]
You're a bit late to the party @GMDuncan ;)

We did originally consider this approach but settled upon a single WFS highlight layer (see discussion at top of this issue and https://github.com/jncc/web-mapper-core/issues/87#issuecomment-518169937).
But given the complexities we've hit with WFS, it might be worth revisiting using WMS with the already applied filter and a point intersect clause.
This does mean adding a separate WMS layer for each active layer that intersects the point. We still need to know the geom column too but you're right that the performance issue would be solved doing it like this.
But I'm also wondering what this is going to look like on the map for EMODnet with multiple layers highlighted that contain very large and irregular polygons.
I'll wait to see what others say but can certainly try this approach.
Don't worry about stepping on toes - we want the best solution we can get!

**Comment by GMDuncan** [comment]
Completely agree with EMODnet multiple layers being a bit of an issue!


Also, picking holes in my own thoughts here - one problem I can see is that I think GeoServer puts a buffer around a getfeatureinfo request by default (something like 2 or 5 pixels?).
As the CQL intersects method above uses an (unbuffered) point, it may be that you get feature info back without a corresponding highlight if you missed the feature slightly (especially with point data?).  I'm not sure there's a way to buffer the intersects point without some costly shenanigans at either end to calculate an n-pixel buffer based on current map scale?

**Comment by helen-lillis** [comment]
> If you have mutiple active layers, then presumably you would have multiple highlighted polygons - one for each layer. I think that would look okay for MPAs but might be very messy or confusing for EMODnet. We could set it so that only the feature on the top layer is selected.

If you set it to only select the layer on top, could you just clarify how that would work, considering that different layers will have different extents? Would it:
a) select whatever feature is on top at the selected location, or
b) only try to select from the layer that is on top in the layer order, even if it doesn't have any polygon at that location?

Ideally it would be (a), as (b) would be confusing for the user.

**Comment by andyb-esdm** [comment]
There's a method on the map called forEachLayerAtPixel and we use it for GetFeatureInfo. It tests which layers have a colour value at the pixel. So the first layer you get would be the top layer with a feature (a) ... I think!
I haven't actually tested to see if it's the top layer first so I shouldn't assume that. But we do know the layer order in the active layers array so that could be worked out.
Still arguably a bit confusing because the featureinfo panel on the right will show feature info from all layers. Also it won't necessarily be the top active layer either.
(I'm surprised how complicated this has turned out to be @JamesPe told me he isn't :) ).

**Comment by HelenwoodsJNCC** [comment]
Thanks for digging into this. I am happy for you to keep working on this @helen-lillis would you agree? Do you think it is worth digging into the WMS option or has Graeme managed to talk himself/you out of it? 

I agree it's a bit confusing that the feature info pane returns everything but the highlighting will only be the top layer. However since that top entry in the feature info pane corresponds to the top layer perhaps it's not so bad? 

Was the plan to have the highlight as a fill for the polygons? Just at the moment I can imagine a scenario whereby the user is zoomed in to look at point data but has a polygon layer on top - they then click and the highlight works on the polygon but it doesn't look like anything has happened.

**Comment by helen-lillis** [comment]
Yes happy to keep going, thanks for the response Andy.

**Comment by andyb-esdm** [comment]
@helen-lillis @HelenwoodsJNCC Okay. You can have any styling you want for WFS. Or, if we opt to go WMS, then I think you can create a style on geoserver (again anything you want). I'll continue the conversation with @GMDuncan before I start on it again.

**Comment by GMDuncan** [comment]
Happy to book in a quick slot at some point to discuss @andyb-esdm if you want (though I'm really not very up to speed with current web mapping tech - I know just about enough to go "oo that looks interesting" and then generally find out it's the wrong option ;) )

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @GMDuncan @JordanPinder @helen-lillis 
Hi all, I tried the WMS approach yesterday.
When you click on the map, the code checks through all the layers under that click, selects the top one and then creates a new layer source for a highlight layer. This source is filtered by a cql_filter which filters geometries that intersect the point you click as @GMDuncan suggested.

This worked well for selecting, but hit a snag with styling. For a single layer, you can add a 'styles= highlight' (for example) to your request. But _I think_ for layer groups the styles can't be set in the request. They seemed to be fixed by the configuration in geoserver. We tried giving layer groups an additional highlight style but couldn't do it. If this is possible, please let me know.

Instead we created a clone of the layer group and set its styles to the highlight style and named it in a predictable way e.g. eusm2016 layer group and eusm2016_highlight layer group.
Then the mapper appends _highlight to the layer name it requests and gets the highlighted style back.

The mapper doesn't know if it's requesting tiles from a layer or layer group since the request is the same. So unfortunately we can't use the styles parameter for layers. Instead we would need to take the same approach for consistency: clone the layer and set its style to the highlight style.

It would be a bit of a faff creating clones of all layers and layer groups but it would work.

The cql_filter can be added to layers that support cql filters no problem. So you won't accidentally highlight features that have been filtered out.

But we hit a more serious issue and haven't found a solution. We have some layers that are based on parameterised sql views (they take a viewParams parameter to filter them) and we weren't able to filter these using a cql_filter.
The cql filter looks like this (where coordinate is the coordinate of your click):

    cqlFilter = `INTERSECTS(geom, SRID=3857;POINT(${coordinate[0]} ${coordinate[1]}))`;

When we tried to apply that to an unfiltered layer based on a sql view we would only get transparent tiles back. When we applied it to a filtered layer (with viewParams set), we got this error:

    <ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://jnccdev-geo.esdm.co.uk:80/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd"
        <ServiceException code="internalError">
            Rendering process failed java.io.IOExceptionorg.postgresql.util.PSQLException: ERROR: Operation on mixed SRID geometries ERROR: Operation on mixed SRID geometries
        </ServiceException>
    </ServiceExceptionReport>

We tried a lot of different combinations of requests (including omitting the SRID). But none worked. It looked promising because it suggested it was attempting to query the database but I'm not sure what's really going on. Nor do I understand why we just got transparent tiles back on an unfiltered sql view with the cql_filter appended.

So I'm a bit stuck at the moment. I don't know if geoserver supports filtering by both viewParams and cql_filter. I didn't find any information from google. If it does, I'm still not sure how to present the cql_filter so we get results back without error (it could be that I just need to transform the point to the native SRID but that will be more config).

I will ask colleagues here but if you have any ideas, please  let me know. Apologies that I haven't been able to get this done for you yet.

It works nicely for the cql filtered layers though.
![image](https://user-images.githubusercontent.com/31621682/74347590-37d8fa80-4da9-11ea-8690-2ab863c28867.png)

**Comment by andyb-esdm** [comment]
Hang on. Writing all that prompted me to look again. We hadn't set the srid on our test layer. I changed it to this:

![image](https://user-images.githubusercontent.com/31621682/74350301-72dd2d00-4dad-11ea-9abe-a1794a7dcbc1.png)

And it works! This returns a tile that is filter by cql_filter and viewParams.

http://jnccdev-geo.esdm.co.uk/geoserver/emodnet/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng8&TRANSPARENT=true&LAYERS=Test&TILED=TRUE&CQL_FILTER=INTERSECTS(geom%2C%20SRID%3D3857%3BPOINT(-4891.969810251147%207394212.368194809))&viewParams=code%3A%27A5.27%27%3B&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=-626172.1357121654%2C6887893.4928338025%2C-1.5133991837501526e-9%2C7514065.628545966

![image](https://user-images.githubusercontent.com/31621682/74350591-d5362d80-4dad-11ea-819b-1821a652fc0f.png)

We would still need to clone all the layers though. Is that acceptable?

**Comment by andyb-esdm** [comment]
Correction from @SimonAnnetts 
You don't have to clone the layers themselves - just layer groups. One with standard styling and one with the highlighted styling and a predictable suffix e.g. _highlight.
For individual layers, just create a new layer group containing it with the original name and the _highlight suffix (plus new highlight styling).

Alternatively we could have something in the layer config that distinguishes between layer groups and layers and then use styles= for layers. But I think I prefer the first approach for consistency.

**Comment by helen-lillis** [comment]
@HelenwoodsJNCC are you able to respond to this? I think this is more for the MPA mapper than EMODnet so I suppose it's up to you to balance up the benefits vs the potential faff of having to duplicate layer groups every time we add or update a layer.

**Comment by GMDuncan** [comment]
Just a last-ditch probably stupid question to avoid layer/group duplication.... No idea if it's sensibile, but thought I'd write it down in case I forget it...

Would it be possible to use geoserver's environment parameters to do this? for example if you're requesting a layer highlighted, **as well as the filter** you would do something like:

`&env=highlight:yes`

Then in every SLD (which should be less than every layergroup? or at least prevent duplication?) you could then add a rule **at the bottom** (I think SLD renders top down?) and use an equalto function that picks up the variable using the env function and says if highlight=yes then render?

The styling of this rule would be the same for all polygons (and all points, lines etc if you care about them).

My brain is a bit fried to remember how to do that in SLD, or actually if it's even possible to use an ogc filter an environment parameter in this way? I'll have a mull-over though...

Any thoughts @andyb-esdm ?

**Comment by GMDuncan** [comment]
Passing through this in the URL

`&env=highlight:True
`
Seems to work in combination with all the CQL above and the following SLD rule at the bottom of the style.

`        <se:Rule>
          <se:Name>Selected Feature</se:Name>
          <ogc:Filter xmlns:ogc="http://www.opengis.net/ogc">
            <ogc:PropertyIsEqualTo>
					<ogc:Function name="env">
					   <ogc:Literal>highlight</ogc:Literal>
					   <ogc:Literal>False</ogc:Literal>
					</ogc:Function>
					<ogc:Literal>True</ogc:Literal>
            </ogc:PropertyIsEqualTo>
          </ogc:Filter>
          <se:PolygonSymbolizer>
            <se:Fill>
              <se:SvgParameter name="fill">#ffff00</se:SvgParameter>
            </se:Fill>
            <se:Stroke>
              <se:SvgParameter name="stroke">#ebd534</se:SvgParameter>
              <se:SvgParameter name="stroke-width">2</se:SvgParameter>
              <se:SvgParameter name="stroke-linejoin">bevel</se:SvgParameter>
            </se:Stroke>
          </se:PolygonSymbolizer>
        </se:Rule>`

The downside is that you end up with an ugly extra 'Highlight' class on your legends, but it might save duplicating layers and groups?

I was wondering if you could actually do it in one without a CQL filter by passing 3 environment parameters to the final rule:...

- highlight 'trigger;
- x position of click
- y position of click

(highlight to really ensure you want the style showing)

...and then combining these with a spatial filter in the SLD (e.g. intersects) to do it in a one-step and letting you just call a single layer instead of doubling the WMS requests? 

But I'm not sure if that would be a) overkill and b) possible.

**Comment by HelenwoodsJNCC** [comment]
@helen-lillis the MPA mapper only has two layer groups and these are both pretty small so it wouldn't be a major issue for us to duplicate the data if required. Are there many EMODnet layer groups? Although perhaps this isn't necessary given @GMDuncan comments above - @andyb-esdm what do you think of the above?

**Comment by helen-lillis** [comment]
> @helen-lillis the MPA mapper only has two layer groups and these are both pretty small so it wouldn't be a major issue for us to duplicate the data if required. Are there many EMODnet layer groups?
Yes I think so. @JordanPinder can confirm.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm just to confirm would the hightlighting features option be the default for all layers? or is it something we could turn on/off in the api?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC sorry for not replying quickly to earlier comments. I haven't investigated (read understood @GMDuncan's comment). We can definitely make this configurable. We could do it on the MapInstance configuration of the api or the config files in assets. I think it would be better as an extra column on the mapinstance table and available over the api.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm happy to have this option added into the api. Just to confirm since it will only be the top layer that is highlighted, there isn't any way of flagging which record is highlighted in the Get feature info pop-up is there?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Okay. We'll tweak the API.
There should be a way to highlight the top layer in the feature info because each is made as a separate request so you get a separate bit of html back for each. I'll have a look at options when I finish this feature off.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Just a quick update. I have the highlighting working okay today. Needed to take into account users switching layers on and off and reordering them. I still need to provide you with the api option to use it and we need to test against our development '_highlight' layers and groups. Oh and a bit of documetation too!
I'll speak to @SimonAnnetts this week to get this finished off on the api/geoserver side.

**Comment by HelenwoodsJNCC** [comment]
Thanks for the update @andyb-esdm, looking forward to having a play around with it. Hope you are keeping well!

**Comment by SimonAnnetts** [comment]
AllowLayerHighlight field added to the MapInstance table. This comes out in the JSON as allowLayerHighlight. Visible here: http://jnccdev-api.esdm.co.uk/api/mapinstance/emodnet

I'll create some highlighted layers on our test geoserver now for demo and testing purposes.

**Comment by HelenwoodsJNCC** [comment]
Hi @andyb-esdm @SimonAnnetts should I be seeing the highlighting on your test instance: https://jnccdev-map.esdm.co.uk/?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Sorry I haven't pushed the changes! Will check it all works and let you know when available (today).

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm Thanks!

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC It's deployed now. Sorry about that.
1. Our highlight styling leaves a bit to be desired but you can choose your own by creating layers/groups with the _highlight suffix. All layers where highlighting is allowed must have a duplicate with _highlight by the way.
2. It also highlights the layer in the getfeatureinfo panel. This isn't particularly lovely at the moment either (a red bar to the left). This could be configurable in the custom css (or tell me what you would like). Unfortunately, I can't put a border around the whole feature info since the content overflows for many layers and it doesn't look good like that. We could add text e.g. 'selected' above the feature info or similar.
4. I found a bug (hence the delay). The featureinfo panel isn't dismissed if you click off all layers e.g. click in mainland GB. But the feature highlight disappears as it should. Fixed now.
3. There is one remaining issue. There is a noticeable lag where you can see the previous highlighted feature as the new one is requested from the WMS. I tried setting the layer source to null to no avail. I think the tiles get cached. OpenLayers 6 has a method to clear this cache but the version we are using doesn't (4.6.5). I think I should see if we can upgrade easily when working on the tree filter controls.

**Comment by HelenwoodsJNCC** [comment]
Thanks @andyb-esdm. A few thoughts on the above:
1.  The duplicate _highlight is this a full duplication of data plus a highlight style? I presume this doesn't need adding to the api in any way it just gets called when clicked? 
2. With the GetFeatureInfo highlight could we try adding text to say 'selected' and possibly have horizontal red lines at the top and bottom of the selected rather than along the left hand side?
3. Great thanks
4. Sounds good to me. 

Any other thoughts @JordanPinder

**Comment by SimonAnnetts** [comment]
@HelenwoodsJNCC 
You do not need to duplicate single layers for highlighting. Just create a new layer group with the name of the original layer and the suffix '_highlight', and add the original layer to this group. Then you can override the style of the layer in the layer list in the group to say 'green'. 

For a layer that is a layer group already, unfortunately you do need to create a new layer group and add all of the layers that the original group contains and set each of their styles in the layers list.

The api doesn't need to know about these layers other than on the Map Instance table there is a 'allowLayerHighlight' boolean field. This instructs the mapper to enable highlighting using the special '_highlight' layer groups.

**Comment by andyb-esdm** [comment]
1. Thanks @SimonAnnetts 
2. Okay I'll try that
...
4. Okay. I'll do that next.

**Comment by HelenwoodsJNCC** [comment]
@SimonAnnetts thanks for the clarification. That is simple enough to implement,  How are the other changes coming along @andyb-esdm ?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC I'm working on a generic hierarchical filter control/tree (#94) that we can use for the mapper (and in another project). Next time I update the test site, I'll update the font to Opens Sans too (#99).

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm just wondering if you had had a play around with implementing point 2 above?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Sorry do you mean indicating the layer that is highlighted in GetFeatureInfo? I added a red border to the layer. It isn't ideal really is it? 
![image](https://user-images.githubusercontent.com/31621682/88185201-909ba180-cc2b-11ea-8b9c-f9a490b59bca.png)

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm I think the plan was to try and make it a bit more obvious which was the selected by: adding text to say 'selected' at the top and possibly have horizontal red lines at the top and bottom of the selected rather than along the left hand side?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC I hit a bit of a problem with upper and lower borders because the getfeatureinfo content overflows the container that it's in. So borders and background colours stop short of the html that comes back with getfeatureinfo. Why I didn't add a selected layer title, I don't know though. I've added that. Here's a screenshot to illustrate the issue:
![image](https://user-images.githubusercontent.com/31621682/88187566-9777e380-cc2e-11ea-9602-b5244a1989f3.png)

**Comment by andyb-esdm** [comment]
I wonder if I can get the container to stretch too ... maybe I didn't try hard enough.

**Comment by andyb-esdm** [comment]
I can. The side effect of this is that the overflow creates scrollbars for each FeatureInfo that overflows. Borders are still shortened but a background colour applies across the whole container. Would something like this be okay? If so - what colour?!
![image](https://user-images.githubusercontent.com/31621682/88190285-01de5300-cc32-11ea-9e85-6e26ae0ff201.png)

**Comment by andyb-esdm** [comment]
For feature info that doesn't overflow - this seems to work quite well.
![image](https://user-images.githubusercontent.com/31621682/88190652-6f8a7f00-cc32-11ea-828a-7d125549fa23.png)

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC I've deployed this change to https://jnccdev-map.esdm.co.uk/ so you can take a look.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm - I think it looks much clearer like this. Can we possibly change the header to 'Selected Feature'. I'm almost tempted to say make it a similar colour to the colour used to highlight the feature but maybe paler e.g. Hex:ccffd8 or does that just look hideous?

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm or could go down the yellow route as users might be more familiar with this for selections in ArcMap/QGIS

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Have you settled on a colour for the highlighted feature in the map? (You set that as the default style on the _highlight layergroups}. If so, then I can copy that for the background. Yellow would be fine :)

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm sorry I forgot that we can set the highlight colour ourselves. Lets go with yellow then. Thanks

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC you might change your mind when you see it ... This is a trivial thing to change though so we can tweak this if necessary while I work on other features.

![image](https://user-images.githubusercontent.com/31621682/88296597-d1acb800-ccf6-11ea-984d-787b39240377.png)

**Comment by HelenwoodsJNCC** [comment]
Ok thanks @andyb-esdm
