### ISSUE TITLE
Hierarchical filtering

### ISSUE THREAD

**Issue by HelenwoodsJNCC** [jncc/web-mapper-core#94]
We briefly discussed this in issue #87 but we would like to revisit this issue now some of the smaller support contract issues are closed.

As a reminder we would like to be able to allow filter selections to include all habitats are finer detail (i.e. child habitats). For example, filtering by A4.1 should return A4.11, A4.12, A4.13 etc. @andyb-esdm you mentioned this would probably need a database change to represent parent-child relationships, a new UI to display a tree and some thought about how all this translates into a filter. Happy to discuss this if it is easier.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Sorry for the delay in my reply.
Yes. I think the database change would be limited to a parent field in the lookup table, referencing the parent habitat. Then we'd build a tree from the data in a new filter component. The user would need to be able to select/deselect nodes and (optionally) all of their children.

- For the filtering itself, the filter control would add all the selected habitats to a 'where hab_code IN (....)' type clause I think. This might make it a very long list though.
- We also considered something like 'where hab_code like A1%' but that would only work with hierarchies that have parents as the prefix and it would break if you had a habitat code of A1 and A11.
- If the first option results in two long a filter we could probably add a view or function in the database that returned which habitats to select as children of any filtered habitat.

I think this would take around a day to implement.

**Comment by helen-lillis** [comment]
@andyb-esdm regarding the second bullet point - this shouldn't be a problem. It only goes from A1-A8.

**Comment by andyb-esdm** [comment]
@helen-lillis Thanks. That's good to know. Ideally, the hierarchy wouldn't be dependent upon the code itself, but that option might prove to be simplest and most practical.

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm we are happy to proceed with the implementation of this.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC Okay. Thanks. I'll schedule it in (and let you know).

**Comment by HelenwoodsJNCC** [comment]
@andyb-esdm great thanks. Just let us know if you need anything from us.

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @GMDuncan
Could you send me a real habitat hierarchy that I can build a tree from for the filter control? It would be good to have something 'real'. Thanks.

**Comment by GMDuncan** [comment]
What format/structure would you like it in?

**Comment by andyb-esdm** [comment]
Hi @GMDuncan Thanks.
'Ideally' an ID, Code, ParentID and Description
But I can handle Code, ParentCode, Description
Text, Excel, JSON are fine.
Once I have a tree building from it, we can discuss how it will work with regards to the filters.

**Comment by GMDuncan** [comment]
Try this one.

[eunis_hierarchy2.txt](https://github.com/jncc/web-mapper-core/files/4785829/eunis_hierarchy2.txt)

**Comment by andyb-esdm** [comment]
@GMDuncan Looks perfect. Thanks for your quick response.

**Comment by andyb-esdm** [comment]
I've bound the EUNIS classification to a test tree filter control and created a test panel for it (thanks @GMDuncan for the data). It's pretty large so still needs some styling to fit in with the filter controls - or perhaps this should pop up. I'll speak to @SimonAnnetts about representing the hierarchy in the database and returning it via the API. We also need to decide how this will work with the filters.

![image](https://user-images.githubusercontent.com/31621682/85606082-b5abed00-b64a-11ea-84d6-386ee733c6ff.png)

**Comment by andyb-esdm** [comment]
@GMDuncan @HelenwoodsJNCC 
@SimonAnnetts and I have discussed the  approach for this again.
Changes to the database and API are straightforward.
The filter table will support a new Type (e.g. 'tree' or 'hierarchy')
The lookup table will need a new optional foreign key column ParentId that references LookupId
The API will expose the filter type so that the mapper knows it needs to present the filter options as a tree instead of a flat list.

Creating the tree is already done (see above) though it takes 1-2 seconds to create all of those controls (there are ~1300 habitats in the sample EUNIS classification).

The challenge is how to keep the query size manageable.
I think this would be a CQL_FILTER and, if possible, we wouldn't want to use a 'where habitatcode in (.....)' because someone could click a node high in the hierarchy (e.g. A) which would mean there would be hundreds of habitat codes in the query, potentially exceeding practical querystring lengths for the WMS request.

Would we be able to use LIKE? e.g. where habitat code LIKE A1* ? This would depend on whether the codes are always prefixed by their parent codes e.g. all codes under A1 start with A1 etc. This would restrict the kind of hierarchies you could use though.
However, then things get a bit trickier if the user starts deselecting nodes e.g they click A1 and the deselect A1.11 (and all it's children). This would need to translate into WHERE habitat code LIKE A1* AND habitat code NOT LIKE A1.11*.
We would need some 'intelligent' code that could frame the query in the right way depending on how nodes have been selected in the tree.

This might not be the best way to go about and would be happy to hear any ideas you may have. We would be happy to have a call with you too if that's more practical.

**Comment by GMDuncan** [comment]
> However, then things get a bit trickier if the user starts deselecting nodes e.g they click A1 and the deselect A1.11 (and all it's children). This would need to translate into WHERE habitat code LIKE A1* AND habitat code NOT LIKE A1.11*.

I suppose firstly question mainly for @HelenwoodsJNCC @JordanPinder is this actually a behaviour that you'd want?

Would an alternative which would make the underlying SQL easier, but might increase the complexity of the UI code, be to disable items below a parent when it is selected? Or equally if you unselect an item, the deselection propagates up the ancestors? I suppose built into this @andyb-esdm  what's the default behaviour when you select an item, does the selection propagate to all the child/grandchild items, or does is there no propagation?

**Comment by andyb-esdm** [comment]
@GMDuncan Currently if you select a parent node, all children etc. are selected too. If you deselect a node, all of its children are deselected but parents/sibliings are unaffected. This is done with a custom function called 'checkNodeAndChildren'. We could equally well have 'checkNodeAndDisableChildren' since the behaviour is under our control. This would only allow the user to select a node and all of its children. But it wouldn't let them just select one node e.g. A1.11.

**Comment by GMDuncan** [comment]
Yes that seems sensible to me (though i'm not up-to-date with any nuances).

So selecting A1 would, in effect show any habitats that are A1 or more "detailed" e.g. A1.1, A1.11, A1.2, A1.3 etc. Then in the mapper's business logic, the checked item is fed through to the CQL query. As only A1 is checked and everything else is unchecked (or disabled) this would as you say become a LIKE 'A1*' statement

To show only A1.1 and A1.3 (and every child habitat underneath) but NOT A1.2 (or its children), a user then deselects A1, and then manually selects both A1.1 and A1.3. This would become LIKE 'A1.1*' OR LIKE 'A1.2*'

There's potentially some issue with mosaic habitats then, but that's probably more of a data management problem as to get around it you'd have to use regex or similar which would be a lot slower?

**Comment by andyb-esdm** [comment]
@GMDuncan 
Yes that's how it would be if selecting a top node meant you included children. I guess this is a business decision more than a technical one though.
Also talked about limiting the number you could select but that would be jarring to the user I suspect.
Posting (instead of getting) the WMS is possible but I think that would be complicated and affect the rest of the application.

We wondered how we could do this with mosaics too and I don't have an answer to that. You would want all mosaics that contain A1.1 and I'm not sure whether LIKE '*A1.1*' would work in all cases or be performant.

I'm carrying on with the data download issue while we settle on requirements.
