### ISSUE TITLE
Update mapper font and font size

### ISSUE THREAD

**Issue by JordanPinder** [jncc/web-mapper-core#99]
Hi Andy,

The EMODnet project is needing us to adhere to some very specific visual identify guidelines. One of the things they've picked up is that our mapper is not in the font and font size as specified by the project (below). 

![image](https://user-images.githubusercontent.com/30415162/78246807-a6048880-74e1-11ea-9e1c-b54346291f6d.png)

Would it be possible to get the font of the EMODnet mapper changed to the Open Sans style?

**Comment by andyb-esdm** [comment]
Hi @JordanPinder Yes. I can do that.

**Comment by andyb-esdm** [comment]
@JordanPinder can you direct me to the style guide in the screenshot for this issue please? I think you told me before but I don't  have it to hand. Thanks.

**Comment by JordanPinder** [comment]
[EMODnet_Visual_IdentityGuidelines.pdf](https://github.com/jncc/web-mapper-core/files/4780540/EMODnet_Visual_IdentityGuidelines.pdf)
I can't remember whether I sent it as an email so I've attached it here :) let me know if you need anything else.

**Comment by andyb-esdm** [comment]
@JordanPinder @HelenwoodsJNCC

I've replaced Montserrat font with Open Sans throughout - unfortunately this isn't something configurable in the customisable CSS currently. But I don't think it changes the look of the site too much. Let me know if MPA mapper _does_ want to stick with Montserrat and I'll change the CSS structure.
All caps in the titles of the panels leaves the letter spacing a bit cramped so I've bumped that up a very small amount (1px -  see below). I think that's allowed.

![image](https://user-images.githubusercontent.com/31621682/84754598-8517e380-afb8-11ea-80c3-c3dc94cd6783.png)

![image](https://user-images.githubusercontent.com/31621682/84754629-8ea14b80-afb8-11ea-8ff6-5903b24051f3.png)


I've also reset font size to 14px (instead of 12px) Here's a before and after. I think the larger font-size looks okay. But let me know if it's okay for both the MPA and EMODnet mappers.

![image](https://user-images.githubusercontent.com/31621682/84755369-81d12780-afb9-11ea-9a13-f889dca36cb6.png)

![image](https://user-images.githubusercontent.com/31621682/84755309-68c87680-afb9-11ea-8ba7-3d05f5bb4db2.png)

Pushed up to our test site for your feedback.

**Comment by JordanPinder** [comment]
Thanks @andyb-esdm - personally I'd prefer size 12 font as it's a little clearer and less noisy, is it possible to keep size 12?

@HelenwoodsJNCC just double checking whether you need/want any of these font changes on the MPA mapper? If not then don't worry :)

**Comment by andyb-esdm** [comment]
@JordanPinder I agree but the original issue was to change font and font-size. The EMODnet guidance said minimum 14px. I'm happy to change it back if we can get away with it!

It is easier to stick with Open Sans with both mappers (Montserrat is only used for the headings). Otherwise I'll need to change how the customisable css works (which I'm happy to do if you need it).

**Comment by andyb-esdm** [comment]
for info
![image](https://user-images.githubusercontent.com/31621682/85038057-0b315700-b17e-11ea-83ec-d647e2e8366c.png)

**Comment by andyb-esdm** [comment]
It looks much better at 12px. I've reverted that change.

**Comment by HelenwoodsJNCC** [comment]
@JordanPinder sorry your question passed me by. We don't need any specific font changes for the MPA mapper. Is this issue resolved?

**Comment by andyb-esdm** [comment]
@HelenwoodsJNCC @JordanPinder All fonts now Open Sans and default to 12px.
